import type { PresetConfig } from "../types/index.js"

export function library(): PresetConfig {
  return {
    name: 'library',
    formats: ['cjs', 'esm'],
    dts: true,
    sourcemap: true,
    platform: 'neutral',
    external: [
      'node:*',
      'fs',
      'path',
      'os',
      'crypto',
      'util',
      'stream',
      'events',
      'child_process',
      'worker_threads',
      'cluster',
      'http',
      'https',
      'net',
      'dgram',
      'dns',
      'tls',
      'readline',
      'repl',
      'tty',
      'zlib',
      'querystring',
      'url',
      'buffer',
      'string_decoder',
      'perf_hooks',
      'vm',
      'assert',
      'async_hooks',
      'console',
      'constants',
      'domain',
      'inspector',
      'module',
      'process',
      'punycode',
      'timers',
      'trace_events',
      'v8',
      'wasi'
    ],
    bundle: false,
    treeshake: true,
    minify: false
  }
}