name: "@akaoio/builder"
description: "Universal TypeScript build framework for the @akaoio ecosystem"
version: "0.0.1"
author: "AKAO Team"
repository: "https://github.com/akaoio/builder"
license: "MIT"